import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { CloseIcon } from '@/components/icons/CloseIcon';
import { BookmarkIcon } from '@/components/icons/BookmarkIcon';
import { CalendarDaysIcon } from '@/components/icons/CalendarDaysIcon';
import { ClipboardDocumentListIcon } from '@/components/icons/ClipboardDocumentListIcon';

const CalendarActionModal = ({ isOpen, onClose, onSelectAction }) => {
    if (!isOpen)
        return null;
    return (_jsx("div", { className: "fixed inset-0 bg-black bg-opacity-60 z-50 flex justify-center items-center p-4", onClick: onClose, children: _jsxs("div", { className: "bg-white rounded-lg shadow-2xl w-full max-w-sm", onClick: e => e.stopPropagation(), children: [_jsxs("div", { className: "p-4 border-b border-slate-200 flex justify-between items-center", children: [_jsx("h2", { className: "text-xl font-bold text-slate-800", children: "Añadir al Calendario" }), _jsx("button", { onClick: onClose, className: "p-2 rounded-full text-slate-500 hover:bg-slate-100", "aria-label": "Cerrar modal", children: _jsx(CloseIcon, {}) })] }), _jsxs("div", { className: "p-6 space-y-4", children: [_jsx("p", { className: "text-slate-600 text-center mb-4", children: "¿Qué deseas agendar para esta fecha?" }), _jsxs("button", { onClick: () => onSelectAction('schedule-visit'), className: "w-full flex items-center text-left p-4 rounded-lg bg-slate-50 hover:bg-green-100 hover:border-green-300 border border-slate-200 transition focus:outline-none focus:ring-2 focus:ring-green-400", children: [_jsx(CalendarDaysIcon, { className: "h-6 w-6 text-green-500" }), _jsxs("div", { className: "ml-4", children: [_jsx("p", { className: "font-semibold text-slate-800", children: "Agendar Nueva Visita" }), _jsx("p", { className: "text-sm text-slate-500", children: "Programa una visita con cliente." })] })] }), _jsxs("button", { onClick: () => onSelectAction('task-add'), className: "w-full flex items-center text-left p-4 rounded-lg bg-slate-50 hover:bg-indigo-100 hover:border-indigo-300 border border-slate-200 transition focus:outline-none focus:ring-2 focus:ring-indigo-400", children: [_jsx(ClipboardDocumentListIcon, { className: "h-6 w-6 text-indigo-500" }), _jsxs("div", { className: "ml-4", children: [_jsx("p", { className: "font-semibold text-slate-800", children: "Registrar Trabajo / Tarea" }), _jsx("p", { className: "text-sm text-slate-500", children: "Tomar fotos, reparaciones, trámites." })] })] }), _jsxs("button", { onClick: () => onSelectAction('event'), className: "w-full flex items-center text-left p-4 rounded-lg bg-slate-50 hover:bg-blue-100 hover:border-blue-300 border border-slate-200 transition focus:outline-none focus:ring-2 focus:ring-blue-400", children: [_jsx(BookmarkIcon, { className: "h-6 w-6 text-blue-500" }), _jsxs("div", { className: "ml-4", children: [_jsx("p", { className: "font-semibold text-slate-800", children: "Crear Nuevo Evento" }), _jsx("p", { className: "text-sm text-slate-500", children: "Recordatorios o reuniones." })] })] })] })] }) }));
};
export default CalendarActionModal;